name: Publish DB2Azure to PyPI

on:
  push:
    branches:
      - master  # Trigger the workflow when code is pushed to the main branch
    tags:
      - 'v*.*.*'  # Trigger on tag push with a version format like v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Specify the version of Python you're using

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install wheel

      # Build the package
      - name: Build DB2Azure package
        run: |
          python setup.py sdist bdist_wheel

      # Publish to PyPI
      - name: Publish to PyPI
        if: github.event_name == 'push'  # Ensure secrets are only used for push events
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python -m pip install --upgrade twine
          twine upload dist/*

      # Verify package upload (optional step)
      - name: Verify package on PyPI
        run: |
          pip install --no-cache-dir DB2Azure
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}